//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_Solution {
    
    
    public partial class Dashboard {
        
        /// <summary>
        /// user_name control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl user_name;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Baluchista;


        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Central;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl North;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl South;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Sou;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Nor;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Cen;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Bal;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl TOTALVISITS;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl recovery;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl sales;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl exis_shops;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl new_shops;
        /// <summary>
        /// Button2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button2;
        
        /// <summary>
        /// datepicker_from control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText datepicker_from;
        
        /// <summary>
        /// datepicker_to control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText datepicker_to;
        
        /// <summary>
        /// DropDownList_Region control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DropDownList_Region;
        
        /// <summary>
        /// subregion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl subregion;

        /// <summary>
        /// DropDownList_SubRegion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList DropDownList_SubRegion;

        protected global::System.Web.UI.WebControls.DropDownList DropDownList_TMO;


        protected global::System.Web.UI.WebControls.DropDownList DropDownList_SE;

        /// <summary>
        /// Button1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button Button1;
        
        /// <summary>
        /// regional_counts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel regional_counts;

        protected global::System.Web.UI.WebControls.Panel Panel3;
    }
}
